#!/bin/bash
DIR=${PWD##*/} 
rm -rf ~/media/raspberry/tmp/$DIR
mkdir ~/media/raspberry/tmp/$DIR
cp -r bin/Debug/netcoreapp3.1/* ~/media/raspberry/tmp/$DIR/
if [ -d wwwroot ] ; then
    cp -r wwwroot ~/media/raspberry/tmp/$DIR/
fi
notify-send "Deployed $DIR"

