#!/bin/bash

if [ -z "$1" ] ; then
    echo -e "\e[31m\e[1mUsage: run folder"
    exit 1
fi

if [ ! -d $1 ] ; then
    echo -e "\e[31m\e[1mCannot find folder '$1'"
    exit 1
fi

cd $1

if [ -d wwwroot ] ; then
	if [ -z "$2" ] ; then
		dotnet $1.dll --urls=http://0.0.0.0:5000
	else
		dotnet $1.dll --urls=http://0.0.0.0:$2
	fi
else    
    dotnet $1.dll
fi

cd ..
