#!/bin/bash

dir=$1
shift

if [ -z "$dir" ] ; then
    echo -e "\e[31m\e[1mUsage: run folder"
    exit 1
fi

if [ ! -d $dir ] ; then
    echo -e "\e[31m\e[1mCannot find folder '$dir'"
    exit 1
fi

cd $dir

if [ -d wwwroot ] ; then
	if [ -z "$1" ] ; then
		dotnet $dir.dll --urls=http://0.0.0.0:5000
	else
		dotnet $dir.dll --urls=http://0.0.0.0:$1
	fi
else    
    dotnet $dir.dll $@
fi

cd ..
